### ISSUE TITLE
Is cometd-nodejs-client scalable?

### ISSUE THREAD

**Issue by aaleksandrov** [cometd/cometd-nodejs-client#21] opened 2020-01-14 10:32 UTC
Hi!
We're using this library with https://github.com/cometd/cometd for fetching server-to-server from Salesforce. And when Salesforce publishes many messages (5k+) our consumer can't process it, runs out of memory etc. 
Is it possible to limit amount of messages received by consumer?

**Comment by sbordet** [comment] 2020-01-14 10:53
Duplicate of cometd/cometd#892.

**Closed as completed by sbordet** 2020-01-14 10:53 UTC
